Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -10,3 +10,6 @@ jobs:
 
      - name: Run a sample github action
        run: echo "this workflow works sucessfully"
+
+     - name: Simulating error
+       run: echo "error taking place"; exit 1
